name: MyCTL Command Request
description: Request a new MyCTL command/subcommand

title: "[MyCTL]: Add `<your command>` command"
labels: ["myctl", "feature request"]
projects: "soymadip/8"
assignees: soymadip

body:
  - type: markdown
    attributes:
      value: "## Please fill in the details below to request a new MyCTL command/subcommand."

  - type: textarea
    id: description
    attributes:
      required: true
      label: Description
      description: What does this command do?
      placeholder: eg. takes screenshot of window.

  - type: input
    id: command
    attributes:
      required: true
      label: Command
      description: The full command (e.g., myctl get snip [active|selection|monitor])
      placeholder: myctl screenshot

  - type: textarea
    id: subcommands
    attributes:
      required: false
      label: Subcommands
      description: Any subcommands you suggest
      placeholder: |
        List subcommands, one per line. eg
        1. `active` - takes ss of active window
        2. `selection` - takes ss of selected area
        3. `monitor` - takes ss of monitor
