name: MyCTL Command Request
description: Request a new MyCTL command/subcommand

title: "[MyCTL] Add <your_command> command"
labels: ["myctl", "feature request"]
projects: "soymadip/8"
assignees: soymadip

body:
  - type: markdown
    attributes:
      value: |
        - **Command**: full command `eg. myctl get snip [area|screen|active]`
        - **Desc**: what it does. eg. Take ScreenShot of selection/winow/screen
        - **subcommands**:
            List of subcommands:
            1. `area`: selection/area (defalut)
            2. `screen`: active screen
            3. `active`: active window
