

# ======================= Layer Rules ============================

layerrule {
  name = Vicinae,Rofi Launcher window

  blur = on
  dim_around = on
  animation = popin 98%
  match:namespace = (vicinae|rofi)
}

layerrule {
  name = UI Animations

  animation = slide top
  match:namespace = logout_dialog
}

layerrule {
  name = Waybar Animation

  animation = slide down
  match:namespace = waybar
}
