#
# __        ___           _                 ____        _
# \ \      / (_)_ __   __| | _____      __ |  _ \ _   _| | ___  ___
#  \ \ /\ / /| | '_ \ / _` |/ _ \ \ /\ / / | |_) | | | | |/ _ \/ __|
#   \ V  V / | | | | | (_| | (_) \ V  V /  |  _ <| |_| | |  __/\__ \
#    \_/\_/  |_|_| |_|\__,_|\___/ \_/\_/   |_| \_\\__,_|_|\___||___/
#
#
# MyDE Window & Layer Rules Configuration


# ======================== Float/Dim Rules ===========================

windowrule = match:class .*, center on
windowrule = match:float on, animation slide up

windowrule = dim_around on , match:focus 1, match:workspace special:scratchpad
windowrule = float on, match:class (?i).*(float|blueman-manager|xdg-desktop-portal|zenity|yad).*
windowrule = float on, match:title .*([Ss]ettings|[Pp]references).*


#------------------- App Specific --------------------

windowrule {
  name = Audio Control Dialog

  float = on
  size = 592 317
  move = (1315) (54)
  match:class = wiremix
}

windowrule {
    name = Network Dialog

    float = on
    size = 571 364
    move = (1318) (45)
    dim_around = off
    match:class = ^(com.network.manager|NetworkManager|nm-connection-editor|Wicd-client.py|wicd-client)$
}

windowrule {
    name = Bluetooth Dialog

    float = on
    size = 571 364
    move = (1229) (45)
    dim_around = off
    match:class = ^(blueman-manager|Blueman-manager)$
}

windowrule {
    name = Float Kasts

    float = on
    size = 1146 770
    dim_around = off
    match:class = org.kde.kasts
}

windowrule {
    name = Ddcui UI

    float = on
    dim_around = on
    match:class = ddcui
}

windowrule {
    name = Float Disk Usage Analyzer

    float = on
    size = 960 619
    match:class = ^(org.gnome.baobab|org.kde.filelight)$
}

windowrule = match:class (?i).*(kdeconnect).*, float on
windowrule {
    name = Float Kde Connect

    size = 459 602
    match:class = (?i).*(org.kdeconnet.app)
}

windowrule {
    name = Float Torrent clients

    float = on
    size = 1200 802
    match:class = (?i).*(ktorrent|transmission-qt)
}

windowrule {
    name = Float, Resize ScreenShot window

    float = on
    pin = on
    dim_around = on
    match:class = satty
}

windowrule {
    name = Float, Resize Picture Viewer

    float = on
    size = 1223 795
    match:class = (org.kde.gwenview|org.nomacs.ImageLounge)
}

windowrule {
    name = Antigravity Brave Window

    float = on
    pin = on
    dim_around = on
    match:class = brave-browser
    match:title = about:blank - Brave
}

windowrule {
    name = KeepassXC window rules

    float = on
    size = 1174 765
    match:class = (?i).*(keepassxc).*
}


#=================== Polkit & File Operation Dialogs =====================

windowrule {
  name = File Operation Dialogs

  float = on
  center = on
  animation = popout
  dim_around = on
  size = 1036 638
  match:title = (?i).*(File Operation|Open File|Open Document|Save File|Save As|Select a Folder|Choose|Upload|Open|Save|Select|Select Recording Directory|Add Folder|Add dir|Add File)(.*)
}

windowrule {
  name = Polkit Operation Dialogs

  float = on
  center = on
  animation = popout
  dim_around = on
  min_size = 520 195
  match:title = (polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1|lxqt-policykit-agent)(.*)
}

# =================== Picture-in-Picture ========================

windowrule {
  name = Picture-in-Picture Rules

  float = on
  pin = on
  animation = slide down
  move = ((monitor_w*0.735)-)
  match:title = ^(Picture-in-Picture)$                 # Float
}

# ===================== No VRR ==========================

windowrule = no_vrr on , match:class mpv
