name: Deploy to GitHub Pages

concurrency:
  group: deploy-docs-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - ".github/workflows/**"
      - "wiki/**"
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

jobs:
  build:
    name: Compile Wiki
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wiki

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
          cache-dependency-path: wiki/package-lock.json

      - name: Install dependencies
        working-directory: ./wiki
        run: npm ci

      - name: Build website
        working-directory: ./wiki
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: wiki/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: myde-wiki

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
