name: Test deployment

on:
  pull_request:
    branches:
      - main
    paths:
      - "wiki/**"

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wiki

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
          cache-dependency-path: wiki/package-lock.json

      - name: Install dependencies
        working-directory: ./wiki
        run: npm ci

      - name: Test build website
        working-directory: ./wiki
        run: npm run build
